// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwWhGhoCUyHIfzYAlC56AHCl7n-V0QGhY',
    appId: '1:132404648897:web:d2d50020a4eee64b44ad40',
    messagingSenderId: '132404648897',
    projectId: 'chat-56490',
    authDomain: 'chat-56490.firebaseapp.com',
    storageBucket: 'chat-56490.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_HfO3gVw4rVCzGFS_rj53B8HpKkaS87g',
    appId: '1:132404648897:android:1d34bb2406eda34444ad40',
    messagingSenderId: '132404648897',
    projectId: 'chat-56490',
    storageBucket: 'chat-56490.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAazF_L7ommQjvIDT14QwYg7yXWKPyDkG4',
    appId: '1:132404648897:ios:56210dfb864e0ac144ad40',
    messagingSenderId: '132404648897',
    projectId: 'chat-56490',
    storageBucket: 'chat-56490.appspot.com',
    iosClientId: '132404648897-4t96v675gcvo74bca0n9me66ihqdap3b.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAazF_L7ommQjvIDT14QwYg7yXWKPyDkG4',
    appId: '1:132404648897:ios:494636bf9152cae944ad40',
    messagingSenderId: '132404648897',
    projectId: 'chat-56490',
    storageBucket: 'chat-56490.appspot.com',
    iosClientId: '132404648897-cgk1chel86cvgveokngd7bpcb1j7rllu.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseChatApp.RunnerTests',
  );
}
